workflows:
    react-native-android:
        name: React Native Android
        max_build_duration: 120
        instance_type: mac_mini_m1
        environment:
          vars:
            PACKAGE_NAME: "io.codemagic.sample.reactnative" # <-- Put your package name here e.g. com.domain.myapp
          node: v19.7.0
        scripts:
            - name: Install npm dependencies and required tools
              script: |
                npm install
                brew install gradle
                brew install openjdk@17
            - name: Set JAVA_HOME
              script: |
                export JAVA_HOME=/usr/local/opt/openjdk@17
            - name: Set Android SDK location
              script: |
                echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
            - name: Build Android release
              script: |
                cd android
                chmod +x gradlew
                ./gradlew assembleRelease
        artifacts:
            - android/app/build/outputs/apk/release/*.apk
